export const TRANSLATIONS = {
  en: {
    brand: 'Discrete Tutor',
    settings: 'Settings',
    login: 'Login',
    signup: 'Sign up',
    title: 'Discrete Math Tutor',
    placeholder: 'Ask your discrete math question...',
    send: 'Send',
    sending: 'Sending…',
    scrollDown: 'Scroll down for resources',
    scrollDownStudent: 'Scroll down for learning resources',
    scrollDownTeacher: 'Scroll down to manage classes',
    resourcesTitle: 'Learning Resources',
    teacherPageTitle: 'My Classes',
    navChat: 'Chat',
    navResources: 'Resources',
    navClasses: 'Classes',
    navHomework: 'Homework',
    navMore: 'More',
    exampleQuestions: 'Example questions',
    refreshExamples: 'Try another set',
    chatUnderstanding: 'Understanding your question',
    chatRetrieving: 'Searching course resources',
    chatQueryingCourse: 'Checking course information',
    chatAnalyzingImage: 'Analyzing the image',
    chatAnalyzingLearning: 'Analyzing learning data',
    chatOrganizing: 'Organizing the answer',
    chatUsingTool: 'Using course tools',
    mermaidRenderFailed: 'Mermaid rendering failed. Source is shown below.',
    mermaidCopySource: 'Copy source',
    mermaidCopied: 'Copied',
    mermaidCopyFailed: 'Copy failed',
    mermaidRegenerate: 'Regenerate diagram',
    mermaidRegenerating: 'Regenerating…',
      mermaidRepairPending: 'You can regenerate after the answer is saved',
      mermaidRepairFailed: 'Diagram regeneration failed',
      mermaidRepairInvalid: 'The regenerated diagram is still invalid. The original source was kept.',
      mermaidSaving: 'Saving the repaired diagram…',
      mermaidSaved: 'Diagram repaired and saved',
      mermaidSaveFailed: 'The diagram was repaired, but saving failed',
      mermaidRetrySave: 'Retry save',
    homeworkPageTitle: 'Homework',
    view: 'View',
    download: 'Download',
    language: 'Language',
    currentScene: 'Current scene',
    resourceChapter: 'Discrete Math Chapter 1',
    resourceDesc: 'Comprehensive overview of fundamental concepts and proofs.',
    filters: {
      All: 'All',
      Slides: 'Slides',
      Notes: 'Notes',
      Practice: 'Practice',
      Books: 'Books'
    },
    auth: {
      loginTitle: 'Welcome Back',
      signupTitle: 'Create Account',
      email: 'School Email',
      emailHint: 'Format: 1234567@tongji.edu.cn',
      code: 'Verification Code',
      sendCode: 'Send Code',
      name: 'Name',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      loginBtn: 'Login',
      signupBtn: 'Sign up',
      loggingIn: 'Logging in…',
      signingUp: 'Creating account…',
      serviceUnavailable: 'The service is not responding. Please try again shortly.',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      backToHome: 'Back to Home',
      roleTitle: 'Are you a student or a teacher?',
      student: 'Student',
      teacher: 'Teacher',
      confirmRole: 'Confirm',
      logout: 'Logout',
      createClass: 'Create Class',
      joinClass: 'Join Class',
      currentClass: 'Current class',
      switchClass: 'Switch class',
      classResourcesFollowHint: 'The resources below follow the class you select here.',
      joinAnotherClass: 'Join another class',
      cancelJoin: 'Cancel',
      resourceLibrary: 'Class resources',
      className: 'Class Name',
      inviteCode: 'Invite Code',
      myClasses: 'My Classes',
      uploadMaterial: 'Upload Material',
      deleteMaterial: 'Delete',
      deleteMaterialConfirm: 'Delete this learning resource? This cannot be undone.',
      materialSort: 'Resource sorting',
      sortBy: 'Sort by',
      sortByName: 'File name',
      sortByUploadedAt: 'Upload time',
      sortDirection: 'Order',
      sortAscending: 'Ascending',
      sortDescending: 'Descending',
      noClasses: 'No classes yet',
      noMaterials: 'No resources yet',
      joinSuccess: 'Joined successfully',
      inviteCodeLabel: 'Invite Code',
      selectClassHint: 'Select a class to view materials',
      studentNoClassHint: 'Join a class with invite code to access materials',
      teacherNoClassHint: 'Create a class to start uploading materials',
      learningTitle: 'Learning Analytics',
      generateMyReport: 'Generate My Report',
      classStudents: 'My Students',
      generateReport: 'Generate Report',
      viewReport: 'View Report',
      generateClassFeedback: 'Generate Class Feedback',
      viewFeedback: 'View Feedback',
      generating: 'Generating...',
      processing: 'Processing...',
      uploading: 'Uploading...',
      uploadSuccess: 'uploaded successfully',
      indexReused: 'added; existing content index reused',
      opening: 'Opening...',
      downloading: 'Downloading...',
      publishing: 'Publishing...',
      submitting: 'Submitting...',
      deleting: 'Deleting...',
      loading: 'Loading...',
      sendingCode: 'Sending...',
      close: 'Close',
      messagesCount: 'Meaningful learning exchanges',
      noStudents: 'No students in class yet',
      expandStudents: 'Expand',
      collapseStudents: 'Collapse',
      addStudent: 'Add student',
      studentEmail: 'Student email',
      removeStudent: 'Remove',
      feedbackHelpful: 'Helpful',
      feedbackUnhelpful: 'Not helpful',
      feedbackCopy: 'Copy',
      welcomeGuest: 'Welcome! Please log in to start chatting.',
      welcomeRolePending: 'Please choose your identity before you start.',
      welcomeStudent: 'Hello! I am your discrete math tutor. I can help explain concepts and answer questions.',
      welcomeTeacher: 'Hello, teacher! I can help answer student questions and support class management.',
      reportTitle: 'Learning Report',
      feedbackTitle: 'Class Feedback',
      newChat: 'New Chat',
      renameChat: 'Rename',
      saveRename: 'Save',
      cancelRename: 'Cancel',
      renameRequired: 'Enter a conversation title',
      renameTooLong: 'Conversation titles can be up to 50 characters',
      historyTitle: 'History',
      noHistory: 'No conversations yet',
      today: 'Today',
      attachImage: 'Image',
      deleteChat: 'Delete',
      deleteChatConfirm: 'Delete this conversation?',
      homeworkTitle: 'Homework',
      publishHomework: 'Publish Homework',
      homeworkName: 'Title',
      homeworkDesc: 'Description (optional)',
      homeworkDue: 'Due date',
      homeworkDueLabel: 'Homework deadline (optional)',
      homeworkAttach: 'Attachment (optional)',
      homeworkFilesSelected: '{count} attachments selected',
      selectedAttachments: 'Selected attachments',
      removeAttachment: 'Remove',
      homeworkAttachments: 'Attachments',
      noHomework: 'No homework yet',
      submitHomework: 'Submit',
      resubmitHomework: 'Resubmit',
      submissionNote: 'Note (optional)',
      uploadSubmission: 'Upload file',
      viewSubmissions: 'Submissions',
      hideSubmissions: 'Hide',
      submitted: 'Submitted',
      notSubmitted: 'Not submitted',
      deleteHomework: 'Delete',
      deleteHomeworkConfirm: 'Delete this homework?',
      downloadAttachment: 'Attachment',
      submissionCount: 'submissions',
    }
  },
  zh: {
    brand: '离散数学助教',
    settings: '设置',
    login: '登录',
    signup: '注册',
    title: '离散数学助教',
    placeholder: '输入你的离散数学问题...',
    send: '发送',
    sending: '发送中…',
    scrollDown: '向下滑动查看资源',
    scrollDownStudent: '向下滑动查看学习资源',
    scrollDownTeacher: '向下滑动管理班级',
    resourcesTitle: '学习资源',
    teacherPageTitle: '我的班级',
    navChat: '对话',
    navResources: '学习资源',
    navClasses: '我的班级',
    navHomework: '作业',
    navMore: '更多',
    exampleQuestions: '示例问题',
    refreshExamples: '换一换',
    chatUnderstanding: '正在理解问题',
    chatRetrieving: '正在检索课程资料',
    chatQueryingCourse: '正在查询课程信息',
    chatAnalyzingImage: '正在分析图片',
    chatAnalyzingLearning: '正在分析学情',
    chatOrganizing: '正在组织回答',
    chatUsingTool: '正在调用课程工具',
    mermaidRenderFailed: 'Mermaid 图表渲染失败，已显示源码。',
    mermaidCopySource: '复制源码',
    mermaidCopied: '已复制',
    mermaidCopyFailed: '复制失败',
    mermaidRegenerate: '重新生成图表',
    mermaidRegenerating: '正在重新生成…',
      mermaidRepairPending: '回答保存后可重新生成',
      mermaidRepairFailed: '图表重新生成失败',
      mermaidRepairInvalid: '重新生成的图表仍无法渲染，已保留原源码',
      mermaidSaving: '正在保存修复结果…',
      mermaidSaved: '图表已修复并保存',
      mermaidSaveFailed: '图表已修复，但保存失败',
      mermaidRetrySave: '重试保存',
    homeworkPageTitle: '作业',
    view: '查看',
    download: '下载',
    language: '语言',
    currentScene: '当前场景',
    resourceChapter: '离散数学 第一章',
    resourceDesc: '涵盖基本概念与证明方法的全面概述。',
    filters: {
      All: '全部',
      Slides: '课件',
      Notes: '讲义',
      Practice: '练习',
      Books: '教材'
    },
    auth: {
      loginTitle: '欢迎回来',
      signupTitle: '创建账号',
      email: '学校邮箱',
      emailHint: '格式：7位学号@tongji.edu.cn',
      code: '验证码',
      sendCode: '获取验证码',
      name: '姓名',
      password: '密码',
      confirmPassword: '确认密码',
      loginBtn: '登录',
      signupBtn: '注册',
      loggingIn: '登录中…',
      signingUp: '正在创建账号…',
      serviceUnavailable: '服务暂时无响应，请稍后再试。',
      noAccount: '还没有账号？',
      hasAccount: '已有账号？',
      backToHome: '返回首页',
      roleTitle: '请问你是学生还是教师？',
      student: '学生',
      teacher: '教师',
      confirmRole: '确认',
      logout: '退出登录',
      createClass: '创建班级',
      joinClass: '加入班级',
      currentClass: '当前班级',
      switchClass: '切换班级',
      classResourcesFollowHint: '下方学习资料将随当前班级同步切换',
      joinAnotherClass: '加入其他班级',
      cancelJoin: '取消',
      resourceLibrary: '班级资源',
      className: '班级名称',
      inviteCode: '邀请码',
      myClasses: '我的班级',
      uploadMaterial: '上传资料',
      deleteMaterial: '删除',
      deleteMaterialConfirm: '确定删除这份学习资料吗？删除后无法恢复。',
      materialSort: '学习资源排序',
      sortBy: '排序依据',
      sortByName: '文件名称',
      sortByUploadedAt: '上传时间',
      sortDirection: '排序方向',
      sortAscending: '升序',
      sortDescending: '降序',
      noClasses: '暂无班级',
      noMaterials: '暂无资料',
      joinSuccess: '加入成功',
      inviteCodeLabel: '邀请码',
      selectClassHint: '选择班级查看资料',
      studentNoClassHint: '输入邀请码加入班级后即可查看学习资料',
      teacherNoClassHint: '创建班级后即可上传和管理学习资料',
      learningTitle: '学情分析',
      generateMyReport: '生成我的学情报告',
      classStudents: '我的学生',
      generateReport: '生成学情报告',
      viewReport: '查看报告',
      generateClassFeedback: '生成班级学情反馈',
      viewFeedback: '查看班级反馈',
      generating: '生成中...',
      processing: '处理中...',
      uploading: '上传中...',
      uploadSuccess: '上传成功',
      indexReused: '已添加到班级，并复用现有内容索引',
      opening: '打开中...',
      downloading: '下载中...',
      publishing: '发布中...',
      submitting: '提交中...',
      deleting: '删除中...',
      loading: '加载中...',
      sendingCode: '发送中...',
      close: '关闭',
      messagesCount: '有效学习交流',
      noStudents: '班级暂无学生',
      expandStudents: '展开',
      collapseStudents: '收起',
      addStudent: '添加学生',
      studentEmail: '学生邮箱',
      removeStudent: '移除',
      feedbackHelpful: '满意',
      feedbackUnhelpful: '不满意',
      feedbackCopy: '复制',
      welcomeGuest: '欢迎使用离散数学助教，请先登录后开始提问。',
      welcomeRolePending: '请先完成身份选择，再开始使用助手。',
      welcomeStudent: '你好，同学！我是你的离散数学助教，可以帮你解答问题并查看学习资料。',
      welcomeTeacher: '你好，老师！我是离散数学助教，可以帮助你解答学生问题，并支持班级管理。',
      reportTitle: '学情报告',
      feedbackTitle: '班级学情反馈',
      newChat: '新对话',
      renameChat: '重命名',
      saveRename: '保存',
      cancelRename: '取消',
      renameRequired: '请输入会话标题',
      renameTooLong: '会话标题不能超过 50 个字符',
      historyTitle: '历史会话',
      noHistory: '暂无历史会话',
      today: '今天',
      attachImage: '图片',
      deleteChat: '删除',
      deleteChatConfirm: '确定删除这条对话吗？',
      homeworkTitle: '作业',
      publishHomework: '发布作业',
      homeworkName: '作业标题',
      homeworkDesc: '作业说明（可选）',
      homeworkDue: '截止日期',
      homeworkDueLabel: '作业截止时间（可选）',
      homeworkAttach: '附件（可选）',
      homeworkFilesSelected: '已选择 {count} 个附件',
      selectedAttachments: '待上传附件',
      removeAttachment: '移除',
      homeworkAttachments: '作业附件',
      noHomework: '暂无作业',
      submitHomework: '提交作业',
      resubmitHomework: '重新提交',
      submissionNote: '文字说明（可选）',
      uploadSubmission: '上传文件',
      viewSubmissions: '查看提交',
      hideSubmissions: '收起',
      submitted: '已提交',
      notSubmitted: '未提交',
      deleteHomework: '删除',
      deleteHomeworkConfirm: '确定删除这份作业吗？',
      downloadAttachment: '下载附件',
      submissionCount: '份提交',
    }
  }
}

export const SCENE_QUOTES = {
  day: {
    en: { text: 'All of mathematics... finds the most secret truths and puts them in the right light.', author: 'Leonhard Euler' },
    zh: { text: '所有的数学……都能发现最隐秘的真理，并将其置于正确的光线下。', author: '欧拉' }
  },
  night: {
    en: { text: 'There are faint stars in the night sky that you can see, but only if you look to the side of where they shine... Maybe truth is just like that.', author: 'Kurt Godel' },
    zh: { text: '夜空中有些微弱的星光，只有当你侧过头去看它们时才能看见……也许真理也是如此。', author: '哥德尔' }
  },
  sunset: {
    en: { text: 'Thought is only a flash between two long nights, but this flash is everything.', author: 'Henri Poincare' },
    zh: { text: '思想只是两次漫漫长夜之间的一道闪电，但这道闪电就是一切。', author: '亨利·庞加莱' }
  },
}

export const RESOURCE_FILTERS = ['All', 'Slides', 'Notes', 'Practice', 'Books']
export const EXAMPLE_PROMPT_GROUPS = {
  zh: {
    student: [
      [
        '为什么蕴含命题只有在前件为真、后件为假时才是假命题？请结合具体例子说明。',
        '如何用反证法证明：若 n² 是偶数，则 n 是偶数？',
        '给定一个二元关系后，怎样依次判断它是否具有自反性、对称性和传递性？',
      ],
      [
        '如何用真值表判断 `(p→q)↔(¬q→¬p)` 是否为重言式？',
        '数学归纳法中的基础步骤和归纳步骤分别起什么作用？缺少其中一步会怎样？',
        '等价关系如何将一个集合划分为等价类？请用模 3 同余关系说明。',
      ],
      [
        '判断一个函数是单射、满射还是双射时，分别需要检查哪些条件？请配合例子说明。',
        '一个连通图在什么条件下存在欧拉通路或欧拉回路？应该如何快速判断？',
        '什么时候应该使用加法原理、乘法原理、排列或组合？请结合具体情形对比说明。',
      ],
    ],
    teacher: [
      ['设计一节“命题逻辑”课的教学流程', '生成一道图论练习题并给出评分要点', '总结学生学习数学归纳法时的常见误区'],
      ['设计集合与关系章节的课堂活动', '生成一道真值表练习并给出参考答案', '设计一组由基础到进阶的组合计数题'],
      ['给出讲解“等价关系”的课堂案例', '设计图论章节的课堂讨论问题', '制定离散数学阶段测验的知识点分布'],
    ],
  },
  en: {
    student: [
      [
        'Why is an implication false only when its premise is true and its conclusion is false? Explain with a concrete example.',
        'How can contradiction prove that if n² is even, then n is even?',
        'For a binary relation, how can reflexivity, symmetry, and transitivity be checked step by step?',
      ],
      [
        'How can a truth table show whether `(p→q)↔(¬q→¬p)` is a tautology?',
        'What roles do the base case and inductive step play in induction, and what fails if either is missing?',
        'How does an equivalence relation partition a set into equivalence classes? Use congruence modulo 3 as an example.',
      ],
      [
        'What conditions distinguish injective, surjective, and bijective functions? Explain with examples.',
        'When does a connected graph have an Euler path or Euler circuit, and how can this be checked quickly?',
        'When should the addition rule, multiplication rule, permutations, or combinations be used? Compare concrete cases.',
      ],
    ],
    teacher: [
      ['Design a lesson flow for propositional logic', 'Create a graph theory exercise with a scoring rubric', 'Summarize common misconceptions about mathematical induction'],
      ['Design a classroom activity for sets and relations', 'Create a truth-table exercise with a reference answer', 'Design a progression of counting problems from basic to advanced'],
      ['Give a classroom example for teaching equivalence relations', 'Design discussion questions for a graph theory lesson', 'Plan the topic distribution for a discrete mathematics assessment'],
    ],
  },
}
